# Site settings
title: Betty Fabre
header-img: img/home-bg.jpg
email: fabre.betty@gmail.com
description: "Personnal website of Betty Fabre, computer sciences student at ISIMA in Clermont Ferrand."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: FabreBetty
github_username:  BetFab
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
- jemoji
